### ISSUE TITLE
fatal error: all goroutines are asleep - deadlock!.

### ISSUE THREAD

**Issue by alameenlr** [xujiajun/nutsdb#103]
**Describe the bug**
I've created a `db` then created a `bucket`.
Code was from your `README.md` document

**To Reproduce**
Steps to reproduce the behavior(Be specific!):
1. Create a `db`
2. Create a `bucket`
3. Put this `code`

Code:
```go
package main

import (
	"fmt"
	"log"

	"github.com/xujiajun/nutsdb"
)

func main() {
	// Open the database located in the /tmp/nutsdb directory.
	// It will be created if it doesn't exist.
	opt := nutsdb.DefaultOptions
	opt.Dir = "/godbs/nutsdb"
	db, err := nutsdb.Open(opt)
	if err != nil {
		log.Fatal(err)
	}
	err = db.Update(func(tx *nutsdb.Tx) error {
		tx, err := db.Begin(true)
		if err != nil {
			return err
		}

		bucket := "tus-block-status"
		key := []byte("foo2")
		val := []byte("bara")

		// Use the transaction.
		if err = tx.Put(bucket, key, val, 60); err != nil {
			// Rollback the transaction.
			tx.Rollback()
		} else {
			// Commit the transaction and check for error.
			if err = tx.Commit(); err != nil {
				tx.Rollback()
				return err
			}
		}
		return nil
	})
	defer db.Close()
	fmt.Println(err)
}
```
**Expected behavior**
`blank`

**What actually happens**
```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_SemacquireMutex(0xc0000f80b4, 0xc000100000, 0x1)
        C:/Program Files/Go/src/runtime/sema.go:71 +0x4e
sync.(*Mutex).lockSlow(0xc0000f80b0)
        C:/Program Files/Go/src/sync/mutex.go:138 +0x10f
sync.(*Mutex).Lock(...)
        C:/Program Files/Go/src/sync/mutex.go:81
sync.(*RWMutex).Lock(0xc0000f80b0)
        C:/Program Files/Go/src/sync/rwmutex.go:111 +0x95
github.com/xujiajun/nutsdb.(*Tx).lock(0xc0000f2100)
        C:/Users/MyName/go/pkg/mod/github.com/xujiajun/nutsdb@v0.6.0/tx.go:550 +0x85
github.com/xujiajun/nutsdb.(*DB).Begin(0xc0000f8000, 0xc0000d7d01, 0xe64d05, 0xc0000f80b0, 0xc0000f20c0)
        C:/Users/MyName/go/pkg/mod/github.com/xujiajun/nutsdb@v0.6.0/tx.go:82 +0x72
main.main.func1(0xc0000f20c0, 0xc0000eef01, 0xc0000f20c0)
        C:/Users/MyName/Desktop/gloang test/work1/nutsdbtest.go:21 +0x48
github.com/xujiajun/nutsdb.(*DB).managed(0xc0000f8000, 0x1, 0xc0000d7eb8, 0x0, 0x800000)
        C:/Users/MyName/go/pkg/mod/github.com/xujiajun/nutsdb@v0.6.0/db.go:880 +0x6d
github.com/xujiajun/nutsdb.(*DB).Update(...)
        C:/Users/MyName/go/pkg/mod/github.com/xujiajun/nutsdb@v0.6.0/db.go:265
main.main()
        C:/Users/MyName/Desktop/gloang test/work1/nutsdbtest.go:20 +0x23e
exit status 2
```

**Information :**
 - OS: `Windows 10 x64`
 - NutsDB Version `0.6.0`

**Comment by xujiajun** [comment]
@alameenlr There's something wrong with the code you wrote,  I modified the code for you. You can try it

```go
package main

import (
    "fmt"
    "log"

    "github.com/xujiajun/nutsdb"
)

func main() {
    // Open the database located in the /tmp/nutsdb directory.
    // It will be created if it doesn't exist.
    opt := nutsdb.DefaultOptions
    opt.Dir = "/godbs/nutsdb"
    db, err := nutsdb.Open(opt)
    if err != nil {
        log.Fatal(err)
    }
    bucket := "bucketDemo"
   if err := db.Update(
        func(tx *nutsdb.Tx) error {
            key := []byte("name1")
            val := []byte("val2")
            return tx.Put(bucket, key, val, 0)
        }); err != nil {
        log.Fatal(err)
    }
 
    fmt.Println(err)
}


```
